routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CkeditorController;
use App\Http\Controllers\Backend\{Auth\LoginController,
    BranchController,
    CertificateController,
    ConfigController,
    ImageController,
    MainInfoController,
    PageController,
    PartnerController,
    PhotoController,
    Post\PostController,
    Project\CategoryController,
    Project\ProjectController,
    ReportController,
    Service\ServiceController,
    SiteController,
    SlideController,
    TagController,
    TranslateController,
    UserController};

Route::middleware(['auth', 'preventBackHistory'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');
    Route::resource('slides', SlideController::class)->except(['show']);
    Route::get('slides/move/{id}/{type}', [SlideController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('slides.move');
    Route::post('slides/image-delete/{id}', [SlideController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('slides.image-delete');

    Route::resource('partners', PartnerController::class)->except(['show']);
    Route::resource('branches', BranchController::class)->except(['show']);
    Route::get('branches/move/{id}/{type}', [PageController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('branches.move');

    Route::post('partners/image-delete/{id}', [PartnerController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('partners.image-delete');

    Route::resource('reports', ReportController::class)->except(['show']);
    Route::post('reports/file-delete/{id}/{lang}', [ReportController::class, 'fileDelete'])
        ->where('id', '[0-9]+')
        ->name('reports.file-delete');

    Route::resource('certificates', CertificateController::class)->except(['show']);
    Route::post('certificates/image-delete/{id}', [CertificateController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('certificates.image-delete');
    Route::post('certificates/file-delete/{id}/{lang}', [CertificateController::class, 'fileDelete'])
        ->where('id', '[0-9]+')
        ->name('certificates.file-delete');

    Route::resource('services', ServiceController::class)->except(['show']);
    Route::get('services/move/{id}/{type}', [ServiceController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('services.move');
    Route::post('services/image-delete/{id}', [ServiceController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('services.image-delete');
    Route::post('services/icon-delete/{id}', [ServiceController::class, 'iconDelete'])
        ->where('id', '[0-9]+')
        ->name('services.icon-delete');

    Route::resource('project-categories', CategoryController::class)->except(['show']);
    Route::get('project-categories/move/{id}/{type}', [CategoryController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('project-categories.move');
    Route::post('project-categories/image-delete/{id}', [CategoryController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('project-categories.image-delete');

    Route::resource('projects', ProjectController::class)->except(['show']);
    Route::post('projects/image-delete/{id}', [ProjectController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('projects.image-delete');

    Route::middleware('can:tagManage')->group(function () {
        Route::get('tag/merge', [TagController::class, 'merge'])
            ->name('tag.merge');
        Route::resource('tag', TagController::class);
    });

    Route::middleware('can:postManage')->group(function () {
        Route::resource('posts', PostController::class);
        Route::get('posts/tag-list', [PostController::class, 'tagList'])
            ->name('posts.tag-list');
        Route::post('posts/image-delete/{id}', [PostController::class, 'imageDelete'])
            ->where('id', '[0-9]+')
            ->name('posts.image-delete');
        Route::post('posts/bg-delete/{id}', [PostController::class, 'backgroundDelete'])
            ->where('id', '[0-9]+')
            ->name('posts.background-delete');
    });

    Route::middleware('can:pageManage')->group(function () {
        Route::resource('pages', PageController::class)->except(['show']);
        Route::post('pages/image-delete/{id}', [PageController::class, 'imageDelete'])
            ->where('id', '[0-9]+')
            ->name('pages.image-delete');
        Route::get('pages/move/{id}/{type}', [PageController::class, 'move'])
            ->where('type', 'up|down')
            ->where('id', '[0-9]+')
            ->name('pages.move');
    });

    Route::middleware('can:userManage')->group(function () {
        Route::post('users/delete-thumb/{id}', [UserController::class, 'deleteThumb'])
            ->name('users.delete-image');
        Route::resource('users', UserController::class);
    });

    Route::middleware('can:mainInfoManage')->group(function () {
        Route::post('main-info/delete-logo/{id}/{lang}', [MainInfoController::class, 'deleteLogo'])
            ->name('main-info.delete-logo');
        Route::post('main-info/delete-favicon/{id}/{lang}', [MainInfoController::class, 'deleteFavicon'])
            ->name('main-info.delete-favicon');
        Route::get('main-info', [MainInfoController::class, 'index'])->name('main-info');
        Route::put('main-info', [MainInfoController::class, 'update'])->name('main-info.update');
    });

    Route::resource('config', ConfigController::class)->middleware('can:configManage')->except(['show']);
    Route::resource('translates', TranslateController::class)->middleware('can:translateManage')->except(['show']);
    Route::resource('images', ImageController::class);

    Route::post('ckeditor/image_upload', [CkeditorController::class, 'upload'])->name('ckeupload');
    Route::post('tinymce/addWidget', [\App\Http\Controllers\TinymceController::class, 'addWidget'])->name('tinymce.addWidget');

    Route::prefix('photos')->name('photos.')->group(function () {
        Route::get('index', [PhotoController::class, 'index'])->name('index');
        Route::get('folder', [PhotoController::class, 'folderIndex'])->name('folder');
        Route::get('trash', [PhotoController::class, 'trashIndex'])->name('trash');
        Route::get('restore', [PhotoController::class, 'restore'])->name('restore');
        Route::post('create', [PhotoController::class, 'create'])->name('create');
        Route::get('update', [PhotoController::class, 'update'])->name('update');
        Route::post('update', [PhotoController::class, 'update'])->name('update.submit');
        Route::post('size', [PhotoController::class, 'size'])->name('size.submit');
        Route::get('create-folder', [PhotoController::class, 'folderCreate'])->name('create-folder');
        Route::get('delete-folder', [PhotoController::class, 'folderDelete'])->name('delete-folder');
        Route::get('update-folder', [PhotoController::class, 'folderUpdate'])->name('update-folder');
        Route::post('update-folder', [PhotoController::class, 'folderUpdate'])->name('update-folder.submit');
        Route::post('create-folder', [PhotoController::class, 'folderCreate'])->name('create-folder.submit');
        Route::post('delete', [PhotoController::class, 'delete'])->name('delete');
        Route::post('soft-delete', [PhotoController::class, 'softDelete'])->name('softDelete');
        Route::post('crop', [PhotoController::class, 'crop'])->name('crop');
        Route::get('sort', [PhotoController::class, 'sort'])->name('sort');
        Route::post('render-gallery', [PhotoController::class, 'renderGallery'])->name('render-gallery');
        Route::post('get-size', [PhotoController::class, 'getSize'])->name('get-size');
    });
});

Route::middleware(['preventBackHistory'])->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.login');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\PostController;
use App\Http\Controllers\Frontend\SiteController;
use App\Http\Controllers\Frontend\ServiceController;
use App\Http\Controllers\Frontend\ProjectController;

Route::prefix(LaravelLocalization::setLocale())->middleware(['localize'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');
    Route::get('/about-us', [\App\Http\Controllers\Frontend\StaticController::class, 'about'])->name('about');
    Route::get('/page/{slug}', [\App\Http\Controllers\Frontend\StaticController::class, 'view'])
        ->where('slug', '[\w\-]+')
        ->name('page');

    Route::get('/services', [ServiceController::class, 'index'])->name('services');
    Route::get('/service/{slug}', [ServiceController::class, 'view'])
        ->where('slug', '[\w\-]+')
        ->name('service');

    Route::get('/posts', [PostController::class, 'index'])->name('posts');
    Route::get('/post/{slug}', [PostController::class, 'view'])
        ->where('slug', '[\w\-]+')
        ->name('post');

    Route::get('/projects', [ProjectController::class, 'index'])
        ->name('projects');
    Route::get('/projects/category/{category}', [ProjectController::class, 'index'])
        ->where('category', '[\w\-]+')
        ->name('project-category');
    Route::get('/project/{slug}', [ProjectController::class, 'view'])
        ->where('slug', '[\w\-]+')
        ->name('project');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    const DEFAULT_THUMB = 'user.png';

    public function getFullNameAttribute()
    {
        return "{$this->name}";
    }

    public static function create($name, $email, $status, $password)
    {

        $model = new static();

        $model->name = $name;
        $model->email = $email;
        $model->status = $status;
        $model->password = Hash::make($password);

        return $model;
    }

    public function edit($name, $email, $password)
    {
        $this->name = $name;
        $this->email = $email;

        if ($password) {
            $this->password = Hash::make($password);
        }
    }

    public function attachThumb($thumb)
    {
        $this->thumb = $thumb;
    }

    public function detachThumb()
    {
        $this->thumb = null;
    }

    public function isAdmin() {
        return $this->roles()->where('name', 'admin')->exists();
    }

    public function posts()
    {
        return $this->hasMany(Post::class,'author_id')->orderByDesc('published_at');
    }
}

app/Http/Controllers/Backend/BaseController.php
<?php

namespace App\Http\Controllers\Backend;

class BaseController
{
}

app/Http/Controllers/Backend/BranchController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Backend;

use Exception;
use RuntimeException;
use App\Models\Branch;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use App\Services\manager\BranchService;
use Itstructure\GridView\DataProviders\EloquentDataProvider;
use App\Http\Requests\Branch\{BranchCreateRequest, BranchUpdateRequest};

class BranchController extends Controller
{
    private $branchService;

    public function __construct(BranchService $branchService)
    {
        $this->branchService = $branchService;
    }

    public function index()
    {
        $query = Branch::query()->withDepth()->defaultOrder();
        $dataProvider = new EloquentDataProvider($query);

        return view('backend.branches.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        return view('backend.branches.create');
    }

    public function store(BranchCreateRequest $request)
    {
        try {
            $this->branchService->create($request);
            return redirect()->route('admin.branches.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.branches.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function show(Branch $branch)
    {
        return view('backend.branches.view', [
            'branch' => $branch
        ]);
    }

    public function edit(Branch $branch)
    {
        return view('backend.branches.update', compact('branch'));
    }

    public function update(BranchUpdateRequest $request, Branch $branch)
    {
        try {
            $this->branchService->update($request, $branch);
            return redirect()->route('admin.branches.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.branches.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function destroy(Branch $branch): RedirectResponse
    {
        try {
            $this->branchService->remove($branch);
            return redirect()->route('admin.branches.index');
        } catch (RuntimeException $e) {
            return redirect()->route('admin.branches.index');
        }
    }

    public function move(int $id, string $type): RedirectResponse
    {
        $branch = Branch::findOrFail($id);
        ($type == 'up') ? $branch->up() : $branch->down();

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/CertificateController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Backend;

use Exception;
use RuntimeException;
use App\Models\Certificate;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use App\Services\manager\CertificateService;
use Itstructure\GridView\DataProviders\EloquentDataProvider;
use App\Http\Requests\Certificate\{CertificateCreateRequest, CertificateUpdateRequest};

class CertificateController extends Controller
{
    public function __construct(private CertificateService $certificateService)
    {
    }

    public function index()
    {
        $query = Certificate::query()->orderByDesc('id');
        $dataProvider = new EloquentDataProvider($query);

        return view('backend.certificates.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        return view('backend.certificates.create');
    }

    public function store(CertificateCreateRequest $request)
    {
        try {
            $this->certificateService->create($request);
            return redirect()->route('admin.certificates.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.certificates.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function edit(Certificate $certificate)
    {
        return view('backend.certificates.update', compact('certificate'));
    }

    public function update(CertificateUpdateRequest $request, Certificate $certificate)
    {
        try {
            $this->certificateService->update($request, $certificate);
            return redirect()->route('admin.certificates.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.certificates.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function destroy(Certificate $certificate): RedirectResponse
    {
        try {
            $this->certificateService->remove($certificate);
            return redirect()->route('admin.certificates.index');
        } catch (RuntimeException $e) {
            return redirect()->route('admin.certificates.index');
        }
    }

    public function move(int $id, string $type): RedirectResponse
    {
        $page = Certificate::findOrFail($id);
        ($type == 'up') ? $page->up() : $page->down();

        return redirect()->back();
    }

    public function imageDelete(int $id)
    {
        try {
            $this->certificateService->removeImage($id);
            return response()->json(['success' => true]);
        } catch (RuntimeException $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage()
            ]);
        }
    }

    public function fileDelete(int $id, string $lang)
    {
        try {
            $this->certificateService->removeFile($id, $lang);
            return response()->json(['success' => true]);
        } catch (RuntimeException $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage()
            ]);
        }
    }
}

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title') | Admin Panel</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    @include('backend.layouts.styles')
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{{ route('admin.home') }}" class="brand-link">
            <img src="{{ asset('images/AdminLogo.png') }}" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">@lang('admin_panel_name')</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{{ user_image(auth()->user()->thumb) }}" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="{{ route('admin.users.show', auth()->id()) }}" class="d-block">{{ auth()->user()->full_name }}</a>
                </div>
            </div>

            @include('backend.layouts.menu')

        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        @include('backend.layouts.breadcrumb')

        <button class="open-menu"><img src="/images/menu.svg" alt="icon"></button>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                @include('backend.layouts.notification')
                @yield('content')
            </div><!-- /.container-fluid -->
        </section>
    </div>

    @include('backend.layouts.footer')

    @yield('end_load')
</div>
<!-- ./wrapper -->
    @include('backend.layouts.scripts')
</body>
</html>

resources/views/backend/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Panel</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/fontawesome/css/all.min.css') }}">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/icheck-bootstrap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('assets/backend/css/adminlte.min.css') }}">
</head>
<body class="hold-transition login-page">

    @yield('content')


    <!-- jQuery -->
    <script src="{{ asset('assets/backend/js/jquery.min.js') }}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('assets/backend/js/bootstrap.bundle.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('assets/backend/js/adminlte.min.js') }}"></script>
</body>
</html>

resources/views/backend/layouts/breadcrumb.blade.php
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">@yield('title')</h1>
            </div><!-- /.col -->
            @if(!Route::is('admin.home'))
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">{{ trans('admin.home_page') }}</a></li>
                        @hasSection('title')
                            <li class="breadcrumb-item active">@yield('title')</li>
                        @endif
                    </ol>
                </div><!-- /.col -->
            @endif
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

resources/views/backend/layouts/footer.blade.php
<!-- Sidebar Menu -->
<footer class="main-footer">
    <strong>Copyright &copy; 2021.</strong>
    All rights reserved.
</footer>
<!-- /.sidebar-menu -->

resources/views/backend/layouts/menu.blade.php
@php
    /** @var \App\Models\User $user */
    $user = auth()->user();
@endphp
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class  with font-awesome or any other icon font library -->
        <li class="nav-item">
            <a href="{{ route('admin.slides.index') }}" class="nav-link">
                <i class="nav-icon fas fa-images"></i>
                <p>
                    @lang('admin.menu.slides')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.posts.index') }}" class="nav-link">
                <i class="nav-icon fas fa-newspaper"></i>
                <p>
                    @lang('admin.menu.posts')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="javascript:void(0);" class="nav-link">
                <i class="nav-icon fas fa-clipboard-list"></i>
                <p>
                    @lang('admin.menu.projects')
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('admin.project-categories.index') }}" class="nav-link">
                        <p>
                            <i class="nav-icon">-</i>
                            @lang('admin.menu.categories')
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.projects.index') }}" class="nav-link">
                        <p>
                            <i class="nav-icon">-</i>
                            @lang('admin.menu.projects')
                        </p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.services.index') }}" class="nav-link">
                <i class="nav-icon fas fa-users-cog"></i>
                <p>
                    @lang('admin.menu.services')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.certificates.index') }}" class="nav-link">
                <i class="nav-icon fas fa-certificate"></i>
                <p>
                    @lang('admin.menu.certificates')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.reports.index') }}" class="nav-link">
                <i class="nav-icon fas fa-file-archive"></i>
                <p>
                    @lang('admin.menu.reports')
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('admin.partners.index') }}" class="nav-link">
                <i class="nav-icon fas fa-users"></i>
                <p>
                    @lang('admin.menu.partners')
                </p>
            </a>
        </li>

        @if($user->can('pageManage'))
            <li class="nav-item">
                <a href="{{ route('admin.pages.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-book"></i>
                    <p>
                        @lang('admin.menu.pages')
                    </p>
                </a>
            </li>
        @endif
        <li class="nav-item">
            <a href="{{ route('admin.branches.index') }}" class="nav-link">
                <i class="nav-icon fas fa-map"></i>
                <p>
                    @lang('admin.menu.branches')
                </p>
            </a>
        </li>
        @if($user->can('userManage'))
            <li class="nav-item">
                <a href="{{ route('admin.users.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-user"></i>
                    <p>
                        @lang('admin.menu.users')
                    </p>
                </a>
            </li>
        @endif

        <li class="nav-item">
            <a href="javascript:void(0);" class="nav-link">
                <i class="nav-icon fas fa-cogs"></i>
                <p>
                    @lang('admin.menu.settings')
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                @if($user->can('mainInfoManage'))
                    <li class="nav-item">
                        <a href="{{ route('admin.main-info') }}" class="nav-link">
                            <p>
                                <i class="nav-icon">-</i>
                                @lang('admin.menu.main-info')
                            </p>
                        </a>
                    </li>
                @endif
                @if($user->can('configManage'))
                    <li class="nav-item">
                        <a href="{{ route('admin.config.index') }}" class="nav-link">
                            <p>
                                <i class="nav-icon">-</i>
                                @lang('admin.menu.configs')
                            </p>
                        </a>
                    </li>
                @endif
                @if($user->can('translateManage'))
                    <li class="nav-item">
                        <a href="{{ route('admin.translates.index') }}" class="nav-link">
                            <p>
                                <i class="nav-icon">-</i>
                                @lang('admin.menu.translates')
                            </p>
                        </a>
                    </li>
                @endif
                <li class="nav-item">
                    <a href="{{ route('admin.images.index') }}" class="nav-link">
                        <p>
                            <i class="nav-icon">-</i>
                            @lang('admin.menu.images')
                        </p>
                    </a>
                </li>
            </ul>
        </li>
    </ul>


    <a data-href="{{ route('admin.logout') }}" id="logout-button">{{ trans('admin.logout') }}</a>
</nav>

resources/views/backend/layouts/notification.blade.php
@if(session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/backend/layouts/styles.blade.php
<link rel="stylesheet" href="{{ asset('assets/backend/css/fontawesome/css/all.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/daterangepicker.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/fileinput.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/tempusdominus-bootstrap-4.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/adminlte.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/OverlayScrollbars.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/backend/css/dropzone.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.min.css" crossorigin="anonymous">
<link rel="stylesheet" href="/assets/backend/css/admin.css?v=5">