routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CkeditorController;
use App\Http\Controllers\Backend\{Auth\LoginController,
    BranchController,
    CertificateController,
    ConfigController,
    ImageController,
    MainInfoController,
    PageController,
    PartnerController,
    PhotoController,
    Post\PostController,
    Project\CategoryController,
    Project\ProjectController,
    ReportController,
    Service\ServiceController,
    SiteController,
    SlideController,
    TagController,
    TranslateController,
    UserController};

Route::middleware(['auth', 'preventBackHistory'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');
    Route::resource('slides', SlideController::class)->except(['show']);
    Route::get('slides/move/{id}/{type}', [SlideController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('slides.move');
    Route::post('slides/image-delete/{id}', [SlideController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('slides.image-delete');

    Route::resource('partners', PartnerController::class)->except(['show']);
    Route::resource('branches', BranchController::class)->except(['show']);
    Route::get('branches/move/{id}/{type}', [PageController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('branches.move');

    Route::post('partners/image-delete/{id}', [PartnerController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('partners.image-delete');

    Route::resource('reports', ReportController::class)->except(['show']);
    Route::post('reports/file-delete/{id}/{lang}', [ReportController::class, 'fileDelete'])
        ->where('id', '[0-9]+')
        ->name('reports.file-delete');

    Route::resource('certificates', CertificateController::class)->except(['show']);
    Route::post('certificates/image-delete/{id}', [CertificateController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('certificates.image-delete');
    Route::post('certificates/file-delete/{id}/{lang}', [CertificateController::class, 'fileDelete'])
        ->where('id', '[0-9]+')
        ->name('certificates.file-delete');

    Route::resource('services', ServiceController::class)->except(['show']);
    Route::get('services/move/{id}/{type}', [ServiceController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('services.move');
    Route::post('services/image-delete/{id}', [ServiceController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('services.image-delete');
    Route::post('services/icon-delete/{id}', [ServiceController::class, 'iconDelete'])
        ->where('id', '[0-9]+')
        ->name('services.icon-delete');

    Route::resource('project-categories', CategoryController::class)->except(['show']);
    Route::get('project-categories/move/{id}/{type}', [CategoryController::class, 'move'])
        ->where('type', 'up|down')
        ->where('id', '[0-9]+')
        ->name('project-categories.move');
    Route::post('project-categories/image-delete/{id}', [CategoryController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('project-categories.image-delete');

    Route::resource('projects', ProjectController::class)->except(['show']);
    Route::post('projects/image-delete/{id}', [ProjectController::class, 'imageDelete'])
        ->where('id', '[0-9]+')
        ->name('projects.image-delete');

    Route::middleware('can:tagManage')->group(function () {
        Route::get('tag/merge', [TagController::class, 'merge'])
            ->name('tag.merge');
        Route::resource('tag', TagController::class);
    });

    Route::middleware('can:postManage')->group(function () {
        Route::resource('posts', PostController::class);
        Route::get('posts/tag-list', [PostController::class, 'tagList'])
            ->name('posts.tag-list');
        Route::post('posts/image-delete/{id}', [PostController::class, 'imageDelete'])
            ->where('id', '[0-9]+')
            ->name('posts.image-delete');
        Route::post('posts/bg-delete/{id}', [PostController::class, 'backgroundDelete'])
            ->where('id', '[0-9]+')
            ->name('posts.background-delete');
    });

    Route::middleware('can:pageManage')->group(function () {
        Route::resource('pages', PageController::class)->except(['show']);
        Route::post('pages/image-delete/{id}', [PageController::class, 'imageDelete'])
            ->where('id', '[0-9]+')
            ->name('pages.image-delete');
        Route::get('pages/move/{id}/{type}', [PageController::class, 'move'])
            ->where('type', 'up|down')
            ->where('id', '[0-9]+')
            ->name('pages.move');
    });

    Route::middleware('can:userManage')->group(function () {
        Route::post('users/delete-thumb/{id}', [UserController::class, 'deleteThumb'])
            ->name('users.delete-image');
        Route::resource('users', UserController::class);
    });

    Route::middleware('can:mainInfoManage')->group(function () {
        Route::post('main-info/delete-logo/{id}/{lang}', [MainInfoController::class, 'deleteLogo'])
            ->name('main-info.delete-logo');
        Route::post('main-info/delete-favicon/{id}/{lang}', [MainInfoController::class, 'deleteFavicon'])
            ->name('main-info.delete-favicon');
        Route::get('main-info', [MainInfoController::class, 'index'])->name('main-info');
        Route::put('main-info', [MainInfoController::class, 'update'])->name('main-info.update');
    });

    Route::resource('config', ConfigController::class)->middleware('can:configManage')->except(['show']);
    Route::resource('translates', TranslateController::class)->middleware('can:translateManage')->except(['show']);
    Route::resource('images', ImageController::class);

    Route::post('ckeditor/image_upload', [CkeditorController::class, 'upload'])->name('ckeupload');
    Route::post('tinymce/addWidget', [\App\Http\Controllers\TinymceController::class, 'addWidget'])->name('tinymce.addWidget');

    Route::prefix('photos')->name('photos.')->group(function () {
        Route::get('index', [PhotoController::class, 'index'])->name('index');
        Route::get('folder', [PhotoController::class, 'folderIndex'])->name('folder');
        Route::get('trash', [PhotoController::class, 'trashIndex'])->name('trash');
        Route::get('restore', [PhotoController::class, 'restore'])->name('restore');
        Route::post('create', [PhotoController::class, 'create'])->name('create');
        Route::get('update', [PhotoController::class, 'update'])->name('update');
        Route::post('update', [PhotoController::class, 'update'])->name('update.submit');
        Route::post('size', [PhotoController::class, 'size'])->name('size.submit');
        Route::get('create-folder', [PhotoController::class, 'folderCreate'])->name('create-folder');
        Route::get('delete-folder', [PhotoController::class, 'folderDelete'])->name('delete-folder');
        Route::get('update-folder', [PhotoController::class, 'folderUpdate'])->name('update-folder');
        Route::post('update-folder', [PhotoController::class, 'folderUpdate'])->name('update-folder.submit');
        Route::post('create-folder', [PhotoController::class, 'folderCreate'])->name('create-folder.submit');
        Route::post('delete', [PhotoController::class, 'delete'])->name('delete');
        Route::post('soft-delete', [PhotoController::class, 'softDelete'])->name('softDelete');
        Route::post('crop', [PhotoController::class, 'crop'])->name('crop');
        Route::get('sort', [PhotoController::class, 'sort'])->name('sort');
        Route::post('render-gallery', [PhotoController::class, 'renderGallery'])->name('render-gallery');
        Route::post('get-size', [PhotoController::class, 'getSize'])->name('get-size');
    });
});

Route::middleware(['preventBackHistory'])->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.login');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\PostController;
use App\Http\Controllers\Frontend\SiteController;
use App\Http\Controllers\Frontend\ServiceController;
use App\Http\Controllers\Frontend\ProjectController;

Route::prefix(LaravelLocalization::setLocale())->middleware(['localize'])->group(function () {
    Route::get('/', [SiteController::class, 'index'])->name('home');
    Route::get('/about-us', [\App\Http\Controllers\Frontend\StaticController::class, 'about'])->name('about');
    Route::get('/page/{slug}', [\App\Http\Controllers\Frontend\StaticController::class, 'view'])
        ->where('slug', '[\w\-]+')
        ->name('page');

    Route::get('/services', [ServiceController::class, 'index'])->name('services');
    Route::get('/service/{slug}', [ServiceController::class, 'view'])
        ->where('slug', '[\w\-]+')
        ->name('service');

    Route::get('/posts', [PostController::class, 'index'])->name('posts');
    Route::get('/post/{slug}', [PostController::class, 'view'])
        ->where('slug', '[\w\-]+')
        ->name('post');

    Route::get('/projects', [ProjectController::class, 'index'])
        ->name('projects');
    Route::get('/projects/category/{category}', [ProjectController::class, 'index'])
        ->where('category', '[\w\-]+')
        ->name('project-category');
    Route::get('/project/{slug}', [ProjectController::class, 'view'])
        ->where('slug', '[\w\-]+')
        ->name('project');
});

app/Http/Controllers/Backend/BaseController.php
<?php

namespace App\Http\Controllers\Backend;

class BaseController
{
}

app/Http/Controllers/Backend/BranchController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Backend;

use Exception;
use RuntimeException;
use App\Models\Branch;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use App\Services\manager\BranchService;
use Itstructure\GridView\DataProviders\EloquentDataProvider;
use App\Http\Requests\Branch\{BranchCreateRequest, BranchUpdateRequest};

class BranchController extends Controller
{
    private $branchService;

    public function __construct(BranchService $branchService)
    {
        $this->branchService = $branchService;
    }

    public function index()
    {
        $query = Branch::query()->withDepth()->defaultOrder();
        $dataProvider = new EloquentDataProvider($query);

        return view('backend.branches.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        return view('backend.branches.create');
    }

    public function store(BranchCreateRequest $request)
    {
        try {
            $this->branchService->create($request);
            return redirect()->route('admin.branches.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.branches.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function show(Branch $branch)
    {
        return view('backend.branches.view', [
            'branch' => $branch
        ]);
    }

    public function edit(Branch $branch)
    {
        return view('backend.branches.update', compact('branch'));
    }

    public function update(BranchUpdateRequest $request, Branch $branch)
    {
        try {
            $this->branchService->update($request, $branch);
            return redirect()->route('admin.branches.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.branches.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function destroy(Branch $branch): RedirectResponse
    {
        try {
            $this->branchService->remove($branch);
            return redirect()->route('admin.branches.index');
        } catch (RuntimeException $e) {
            return redirect()->route('admin.branches.index');
        }
    }

    public function move(int $id, string $type): RedirectResponse
    {
        $branch = Branch::findOrFail($id);
        ($type == 'up') ? $branch->up() : $branch->down();

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/CertificateController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Backend;

use Exception;
use RuntimeException;
use App\Models\Certificate;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use App\Services\manager\CertificateService;
use Itstructure\GridView\DataProviders\EloquentDataProvider;
use App\Http\Requests\Certificate\{CertificateCreateRequest, CertificateUpdateRequest};

class CertificateController extends Controller
{
    public function __construct(private CertificateService $certificateService)
    {
    }

    public function index()
    {
        $query = Certificate::query()->orderByDesc('id');
        $dataProvider = new EloquentDataProvider($query);

        return view('backend.certificates.index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function create()
    {
        return view('backend.certificates.create');
    }

    public function store(CertificateCreateRequest $request)
    {
        try {
            $this->certificateService->create($request);
            return redirect()->route('admin.certificates.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.certificates.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function edit(Certificate $certificate)
    {
        return view('backend.certificates.update', compact('certificate'));
    }

    public function update(CertificateUpdateRequest $request, Certificate $certificate)
    {
        try {
            $this->certificateService->update($request, $certificate);
            return redirect()->route('admin.certificates.index')
                ->with('success', trans('form.success.save'));
        } catch (Exception $e) {
            return redirect()->route('admin.certificates.index')
                ->with('error', trans('form.error.save'));
        }
    }

    public function destroy(Certificate $certificate): RedirectResponse
    {
        try {
            $this->certificateService->remove($certificate);
            return redirect()->route('admin.certificates.index');
        } catch (RuntimeException $e) {
            return redirect()->route('admin.certificates.index');
        }
    }

    public function move(int $id, string $type): RedirectResponse
    {
        $page = Certificate::findOrFail($id);
        ($type == 'up') ? $page->up() : $page->down();

        return redirect()->back();
    }

    public function imageDelete(int $id)
    {
        try {
            $this->certificateService->removeImage($id);
            return response()->json(['success' => true]);
        } catch (RuntimeException $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage()
            ]);
        }
    }

    public function fileDelete(int $id, string $lang)
    {
        try {
            $this->certificateService->removeFile($id, $lang);
            return response()->json(['success' => true]);
        } catch (RuntimeException $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage()
            ]);
        }
    }
}

app/Http/Controllers/Backend/MainInfoController.php
<?php

namespace App\Http\Controllers\Backend;

use Exception;
use App\Http\Controllers\Controller;
use App\Repositories\MainInfoRepository;
use App\Services\manager\MainInfoService;
use App\Http\Requests\MainInfo\MainInfoRequest;

class MainInfoController extends Controller
{
    private $mainInfoService;
    private $mainInfoRepository;

    public function __construct(
        MainInfoService $mainInfoService,
        MainInfoRepository $mainInfoRepository
    ) {
        $this->mainInfoService = $mainInfoService;
        $this->mainInfoRepository = $mainInfoRepository;
    }

    public function index()
    {
        return view('backend.main-info.index', [
            'info' => $this->mainInfoRepository->getFirst()
        ]);
    }

    public function update(MainInfoRequest $request)
    {
        $model = $this->mainInfoRepository->getFirst();

        try {
            $this->mainInfoService->update($request, $model);
            $this->mainInfoService->flushCache();

            return redirect()->route('admin.main-info')
                ->with('success', trans('form.success.save'));
        }
        catch(Exception $e) {}
    }

    public function deleteLogo(int $id, string $lang)
    {
        try {
            $this->mainInfoService->deleteLogo($id, $lang);
            return response()->json(trans('admin.success_deleted'));
        } catch(Exception $e) {
            return response()->json($e->getMessage());
        }
    }

    public function deleteFavicon(int $id, string $lang)
    {
        try {
            $this->mainInfoService->deleteFavicon($id, $lang);
            return response()->json(trans('admin.success_deleted'));
        } catch(Exception $e) {
            return response()->json($e->getMessage());
        }
    }
}

resources/views/backend/reports/create.blade.php
@extends('backend.layouts.app')

@section('title', trans('admin.new_report'))

@section('content')
    <div>
        <form action="{{ route('admin.reports.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-8">

                    <div class="card card-primary card-outline card-tabs">
                        <div class="card-header p-0 pt-1 border-bottom-0">
                            <ul class="nav nav-tabs" id="custom-tabs-three-tab" role="tablist">
                                @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $key => $lang)
                                    <li class="nav-item">
                                        <a class="nav-link @if($key == 0) active @endif" id="tab-{{ $lang }}" data-toggle="pill" href="#tablink-{{ $lang }}" role="tab" aria-controls="tablink-{{ $lang }}" aria-selected="true">{{ strtoupper($lang) }}</a>
                                    </li>
                                @endforeach
                            </ul>
                        </div>

                        <div class="card-body">
                            <div class="tab-content" id="custom-tabs-three-tabContent">
                                @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $key => $lang)
                                    <div class="tab-pane fade @if($key == 0) show active @endif" id="tablink-{{ $lang }}" role="tabpanel" aria-labelledby="tab-{{ $lang }}">
                                        <div class="form-group">
                                            <label for="title-{{ $lang }}">@lang('admin.title')</label>
                                            <input type="text" name="title[{{ $lang }}]" id="title-{{ $lang }}" class="form-control @error('title.' . $lang) is-invalid @enderror" value="{{ old('title.' . $lang) }}">

                                            @error('title.' . $lang)
                                                <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>

                                        <div class="form-group">
                                            <label for="file-{{ $lang }}">@lang('admin.file')</label>
                                            <input name="file[{{ $lang }}]" id="file-{{ $lang }}" type="file" class="file_uploader" data-preview-file-type="text">
                                            @error('file.' . $lang)
                                            <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>
                                        <br>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card card-secondary">
                        <div class="card-body">

                            <div class="form-group">
                                <div class="float-right">
                                    <label for="status">@lang('admin.status.status')</label>
                                    <label class="switch switch-success">
                                        <input type="checkbox" name="status" id="status" @if(old('status')=='on') checked @endif>
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                                <div class="clearfix"></div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <input type="submit" value="@lang('admin.save')" class="btn btn-success float-right">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/backend/reports/index.blade.php
@extends('backend.layouts.app')

@section('title', trans('admin.reports'))

@section('content')
    <div class="mt-3">
        {!! grid([
            'dataProvider' => $dataProvider,
            'columnFields' => [
                [
                    'label' => trans('admin.title'),
                    'attribute' => 'title',
                    'value' => function (\App\Models\Report $model) {
                        return $model->title;
                    }
                ],
                [
                    'label' => trans('admin.status.status'),
                    'attribute' => 'status',
                    'value' => function($data) {
                        return \App\Enum\Status::get($data->status);
                    },
                    'filter' => [
                        'class' => Itstructure\GridView\Filters\DropdownFilter::class,
                        'data' => \App\Enum\Status::getList()
                    ]
                ],
                [
                    'label' => '',
                    'class' => \App\Components\Grid\ActionColumn::class,
                    'actionTypes' => [
                        'edit',
                        'delete' => function ($data) {
                            return route('admin.reports.destroy', $data->id);
                        }
                    ]
                ]
            ],
        ]) !!}
    </div>
@endsection

resources/views/backend/reports/update.blade.php
@extends('backend.layouts.app')

@section('title', $report->title)

@section('content')
    <div>
        <form action="{{ route('admin.reports.update', $report->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-8">

                    <div class="card card-primary card-outline card-tabs">
                        <div class="card-header p-0 pt-1 border-bottom-0">
                            <ul class="nav nav-tabs" id="custom-tabs-three-tab" role="tablist">
                                @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $key => $lang)
                                    <li class="nav-item">
                                        <a class="nav-link @if($key == 0) active @endif" id="tab-{{ $lang }}" data-toggle="pill" href="#tablink-{{ $lang }}" role="tab" aria-controls="tablink-{{ $lang }}" aria-selected="true">{{ strtoupper($lang) }}</a>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                        <div class="card-body">
                            <div class="tab-content" id="custom-tabs-three-tabContent">
                                @foreach(LaravelLocalization::getSupportedLanguagesKeys() as $key => $lang)
                                    <div class="tab-pane fade @if($key == 0) show active @endif" id="tablink-{{ $lang }}" role="tabpanel" aria-labelledby="tab-{{ $lang }}">
                                        <div class="form-group">
                                            <label for="title-{{ $lang }}">@lang('admin.title')</label>
                                            <input type="text" value="{{ $report->getTranslation('title', $lang) }}" name="title[{{ $lang }}]" id="title-{{ $lang }}" class="form-control @error('title.' . $lang) is-invalid @enderror">
                                            @error('title.' . $lang)
                                            <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>

                                        <div class="form-group">
                                            <label for="file-{{ $lang }}">@lang('admin.file')</label>
                                            <input
                                                value="{{ $report->getTranslation('file', $lang, false) ? asset('storage/reports/' . $report->getTranslation('file', $lang, false)) : null }}"
                                                name="file[{{ $lang }}]" id="file-{{ $lang }}" type="file"
                                                class="file_uploader  @error('file.' . $lang) is-invalid @enderror"
                                                data-delete="{{ route('admin.reports.file-delete', ['id' => $report->id, 'lang' => $lang]) }}"
                                                data-preview-file-type="text">

                                            @error('file.' . $lang)
                                            <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>
                                        <br>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card card-secondary">
                        <div class="card-body">

                            <div class="form-group">
                                <div class="float-right">
                                    <label for="status">@lang('admin.status.status')</label>
                                    <label class="switch switch-success">
                                        <input type="checkbox" name="status" id="status" @if($report->status == 1) checked @endif>
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                                <div class="clearfix"></div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <input type="submit" value="@lang('admin.save')" class="btn btn-success float-right">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
    </div>
@endsection